---
apiVersion: v1
kind: Secret
metadata:
  name: splunk-kubernetes-logging
  labels:
    app: splunk-kubernetes-logging
    version: 1.4.4
type: Opaque
data:
  splunk_hec_token: 111a8b83-ccd9-4d8f-82ce-a5961ee12d3e
